In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [3]:
df = pd.read_csv("/content/drive/MyDrive/Data/clean_car_evaluation.csv")

In [4]:
df

buying_price maintenance_cost  doors seats boot_space safety decision
0           vhigh            vhigh      2     2      small    low    unacc
1           vhigh            vhigh      2     2      small    med    unacc
2           vhigh            vhigh      2     2      small   high    unacc
3           vhigh            vhigh      2     2        med    low    unacc
4           vhigh            vhigh      2     2        med    med    unacc
...           ...              ...    ...   ...        ...    ...      ...
1723          low              low  5more  more        med    med     good
1724          low              low  5more  more        med   high    vgood
1725          low              low  5more  more        big    low    unacc
1726          low              low  5more  more        big    med     good
1727          low              low  5more  more        big   high    vgood

[1728 rows x 7 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   buying_price      1728 non-null   object
 1   maintenance_cost  1728 non-null   object
 2   doors             1728 non-null   object
 3   seats             1728 non-null   object
 4   boot_space        1728 non-null   object
 5   safety            1728 non-null   object
 6   decision          1728 non-null   object
dtypes: object(7)
memory usage: 94.6+ KB


In [6]:
for col in df.columns:
  print(col,df[col].nunique())
  print(col,df[col].unique())

buying_price 4
buying_price ['vhigh' 'high' 'med' 'low']
maintenance_cost 4
maintenance_cost ['vhigh' 'high' 'med' 'low']
doors 4
doors ['2' '3' '4' '5more']
seats 3
seats ['2' '4' 'more']
boot_space 3
boot_space ['small' 'med' 'big']
safety 3
safety ['low' 'med' 'high']
decision 4
decision ['unacc' 'acc' 'vgood' 'good']


In [7]:
x = df.drop(columns=['decision'])
y = df['decision']

In [8]:
hoe = OneHotEncoder(drop='first',sparse=False)
x_features = hoe.fit_transform(x)
x_encoded = pd.DataFrame(x_features,columns=hoe.get_feature_names_out(x.columns))
x_encoded

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


buying_price_low  buying_price_med  buying_price_vhigh  \
0                  0.0               0.0                 1.0   
1                  0.0               0.0                 1.0   
2                  0.0               0.0                 1.0   
3                  0.0               0.0                 1.0   
4                  0.0               0.0                 1.0   
...                ...               ...                 ...   
1723               1.0               0.0                 0.0   
1724               1.0               0.0                 0.0   
1725               1.0               0.0                 0.0   
1726               1.0               0.0                 0.0   
1727               1.0               0.0                 0.0   

      maintenance_cost_low  maintenance_cost_med  maintenance_cost_vhigh  \
0                      0.0                   0.0                     1.0   
1                      0.0                   0.0                     1.0   
2                      0.0                   0.0                     1.0   
3                      0.0                   0.0                     1.0   
4                      0.0                   0.0                     1.0   
...                    ...                   ...                     ...   
1723                   1.0                   0.0                     0.0   
1724                   1.0                   0.0                     0.0   
1725                   1.0                   0.0                     0.0   
1726                   1.0                   0.0                     0.0   
1727                   1.0                   0.0                     0.0   

      doors_3  doors_4  doors_5more  seats_4  seats_more  boot_space_med  \
0         0.0      0.0          0.0      0.0         0.0             0.0   
1         0.0      0.0          0.0      0.0         0.0             0.0   
2         0.0      0.0          0.0      0.0         0.0             0.0   
3         0.0      0.0          0.0      0.0         0.0             1.0   
4         0.0      0.0          0.0      0.0         0.0             1.0   
...       ...      ...          ...      ...         ...             ...   
1723      0.0      0.0          1.0      0.0         1.0             1.0   
1724      0.0      0.0          1.0      0.0         1.0             1.0   
1725      0.0      0.0          1.0      0.0         1.0             0.0   
1726      0.0      0.0          1.0      0.0         1.0             0.0   
1727      0.0      0.0          1.0      0.0         1.0             0.0   

      boot_space_small  safety_low  safety_med  
0                  1.0         1.0         0.0  
1                  1.0         0.0         1.0  
2                  1.0         0.0         0.0  
3                  0.0         1.0         0.0  
4                  0.0         0.0         1.0  
...                ...         ...         ...  
1723               0.0         0.0         1.0  
1724               0.0         0.0         0.0  
1725               0.0         1.0         0.0  
1726               0.0         0.0         1.0  
1727               0.0         0.0         0.0  

[1728 rows x 15 columns]

In [9]:
x_train,x_test,y_train,y_test= train_test_split(x_encoded,y,test_size=0.27,random_state=42)
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((1261, 15), (467, 15), (1261,), (467,))

In [10]:
model = SVC()
model.fit(x_train,y_train)

SVC()

In [11]:
y_pred = model.predict(x_test)
y_pred.shape

(467,)

In [12]:
acc = accuracy_score(y_test,y_pred)
acc

0.9400428265524625

In [13]:
print(confusion_matrix(y_test,y_pred))

[[ 98   7   4   1]
 [  4  11   0   2]
 [  5   0 313   0]
 [  5   0   0  17]]


In [14]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         acc       0.88      0.89      0.88       110
        good       0.61      0.65      0.63        17
       unacc       0.99      0.98      0.99       318
       vgood       0.85      0.77      0.81        22

    accuracy                           0.94       467
   macro avg       0.83      0.82      0.83       467
weighted avg       0.94      0.94      0.94       467

